begin
    REHAB_CONTEXT_PKG.set_current_user('YURI');
    REHAB_CONTEXT_PKG.set_specific_context('OLYAPTAH');
end;
/
select
  SYS_CONTEXT('REHAB20_CONTEXT', 'APEX_USER') APEX_USER,
  SYS_CONTEXT('REHAB20_CONTEXT', 'TENANT') qTENANT,
  SYS_CONTEXT('REHAB20_CONTEXT', 'PATIENT') PATIENT,
  SYS_CONTEXT('REHAB20_CONTEXT', 'MODE') qMODE,
  REHAB_CONTEXT_PKG.getAPEX_USER a1,
  REHAB_CONTEXT_PKG.getTENANT a2,
  REHAB_CONTEXT_PKG.getPATIENT a3,
  REHAB_CONTEXT_PKG.getMODE a4,
  REHAB_CONTEXT_PKG.AccessLevelRW a5, 
  REHAB_CONTEXT_PKG.AccessLevelRO a6
from dual;

select PAT_NAME d, PAT_APEX_USER r from REHAB_PATIENTS where (select PAT_IS_SUPERUSER from REHAB_PATIENTS where PAT_APEX_USER=REHAB_CONTEXT_PKG.getCURR_APEX_USER)
union 
select PAT_NAME d, PAT_APEX_USER r from REHAB_PATIENTS where PAT_TE_ID in (select PAT_TE_ID from REHAB_PATIENTS where PAT_APEX_USER=REHAB_CONTEXT_PKG.getCURR_APEX_USER and PAT_IS_TENANTADM)
union 
select PAT_NAME d, PAT_APEX_USER r from REHAB_PATIENTS where PAT_ID in (select P2PA_TRG_PAT_ID from REHAB_PATIENTS2P_ACCESS where P2PA_SUBJ_PAT_ID=REHAB_CONTEXT_PKG.getCURR_PATIENT)
union 
select PAT_NAME d, PAT_APEX_USER r from REHAB_PATIENTS where PAT_APEX_USER=REHAB_CONTEXT_PKG.getCURR_APEX_USER
order by d;