begin
    REHAB_CONTEXT_PKG.set_current_user('YURI');
    REHAB_CONTEXT_PKG.set_specific_context('OLYAPTAH');
end;
/
select
  SYS_CONTEXT('REHAB20_CONTEXT', 'APEX_USER') APEX_USER,
  SYS_CONTEXT('REHAB20_CONTEXT', 'TENANT') qTENANT,
  SYS_CONTEXT('REHAB20_CONTEXT', 'PATIENT') PATIENT,
  SYS_CONTEXT('REHAB20_CONTEXT', 'MODE') qMODE,
  REHAB_CONTEXT_PKG.getAPEX_USER a1,
  REHAB_CONTEXT_PKG.getTENANT a2,
  REHAB_CONTEXT_PKG.getPATIENT a3,
  REHAB_CONTEXT_PKG.getMODE a4,
  REHAB_CONTEXT_PKG.AccessLevelRW a5, 
  REHAB_CONTEXT_PKG.AccessLevelRO a6
from dual;