

  CREATE TABLE "APEX_STORED_STATES"
   (	"STORAGE_ID" NUMBER,
	"APP_USER" VARCHAR2(128 BYTE) NOT NULL ENABLE,
	"APP_PAGE" NUMBER NOT NULL ENABLE,
	"STORAGE_TYPE" VARCHAR2(30 BYTE) NOT NULL ENABLE,
	"STORAGE_NAME" VARCHAR2(30 BYTE) NOT NULL ENABLE,
	"STORAGE_UPDATED" TIMESTAMP (6) WITH TIME ZONE NOT NULL ENABLE,
	"PARAMS" JSON
   ) SEGMENT CREATION DEFERRED
   PCTUSED 40 INITRANS 10 MAXTRANS 255
 NOCOMPRESS  LOGGING
 JSON ("PARAMS") STORE AS ( CHUNK 8192) ;
ALTER TABLE "APEX_STORED_STATES" ADD CHECK (storage_type in ('DEFAULT','USERDEFINED')) ENABLE;
ALTER TABLE "APEX_STORED_STATES" ADD CONSTRAINT "APEX_STORED_STATES_PK" PRIMARY KEY ("STORAGE_ID")
  USING INDEX  INITRANS 20 MAXTRANS 255  ENABLE;
  INSERT /*+  APPEND  NESTED_TABLE_SET_REFS  */ INTO
  "APEX_STORED_STATES"  KUT$ ("STORAGE_ID", "APP_USER", "APP_PAGE", "STORAGE_TYPE", "STORAGE_NAME", "STORAGE_UPDATED", "PARAMS")
  SELECT /*+ NESTED_TABLE_GET_REFS  */
  "STORAGE_ID", "APP_USER", "APP_PAGE", "STORAGE_TYPE", "STORAGE_NAME", "STORAGE_UPDATED", "PARAMS" FROM "APEX_STORED_STATES"@ KU$;


  CREATE GLOBAL TEMPORARY TABLE "ORA$SA$TE_REHAB_CONSUME_PATTERNS"
   (	"DMLTYPE$$" VARCHAR2(1 BYTE),
	"OLD_NEW$$" VARCHAR2(1 BYTE),
	"SEQUENCE$$" NUMBER,
	"CHANGE_VECTOR$$" RAW(513),
	"ROW$$" ROWID,
	"LROWID$$" ROWID,
	"HROWID$$" ROWID,
	"CP_TE_ID" NUMBER,
	"CP_PAT_ID" NUMBER
   ) ON COMMIT DELETE ROWS ;
  INSERT /*+  APPEND  NESTED_TABLE_SET_REFS  */ INTO
  "ORA$SA$TE_REHAB_CONSUME_PATTERNS"  KUT$ ("DMLTYPE$$", "OLD_NEW$$", "SEQUENCE$$", "CHANGE_VECTOR$$", "ROW$$", "LROWID$$", "HROWID$$", "CP_TE_ID", "CP_PAT_ID")
  SELECT /*+ NESTED_TABLE_GET_REFS  */
  "DMLTYPE$$", "OLD_NEW$$", "SEQUENCE$$", "CHANGE_VECTOR$$", "ROW$$", "LROWID$$", "HROWID$$", "CP_TE_ID", "CP_PAT_ID" FROM "ORA$SA$TE_REHAB_CONSUME_PATTERNS"@ KU$;


  CREATE GLOBAL TEMPORARY TABLE "ORA$SA$TE_REHAB_DRUG_USES"
   (	"DMLTYPE$$" VARCHAR2(1 BYTE),
	"OLD_NEW$$" VARCHAR2(1 BYTE),
	"SEQUENCE$$" NUMBER,
	"CHANGE_VECTOR$$" RAW(513),
	"ROW$$" ROWID,
	"LROWID$$" ROWID,
	"HROWID$$" ROWID,
	"DRU_PR_ID" NUMBER,
	"DRU_PAT_ID" NUMBER
   ) ON COMMIT DELETE ROWS ;
  INSERT /*+  APPEND  NESTED_TABLE_SET_REFS  */ INTO
  "ORA$SA$TE_REHAB_DRUG_USES"  KUT$ ("DMLTYPE$$", "OLD_NEW$$", "SEQUENCE$$", "CHANGE_VECTOR$$", "ROW$$", "LROWID$$", "HROWID$$", "DRU_PR_ID", "DRU_PAT_ID")
  SELECT /*+ NESTED_TABLE_GET_REFS  */
  "DMLTYPE$$", "OLD_NEW$$", "SEQUENCE$$", "CHANGE_VECTOR$$", "ROW$$", "LROWID$$", "HROWID$$", "DRU_PR_ID", "DRU_PAT_ID" FROM "ORA$SA$TE_REHAB_DRUG_USES"@ KU$;


  CREATE GLOBAL TEMPORARY TABLE "ORA$SA$TE_REHAB_PATIENTS"
   (	"DMLTYPE$$" VARCHAR2(1 BYTE),
	"OLD_NEW$$" VARCHAR2(1 BYTE),
	"SEQUENCE$$" NUMBER,
	"CHANGE_VECTOR$$" RAW(513),
	"ROW$$" ROWID,
	"LROWID$$" ROWID,
	"HROWID$$" ROWID,
	"PAT_TE_ID" NUMBER,
	"PAT_ID" NUMBER
   ) ON COMMIT DELETE ROWS ;
  INSERT /*+  APPEND  NESTED_TABLE_SET_REFS  */ INTO
  "ORA$SA$TE_REHAB_PATIENTS"  KUT$ ("DMLTYPE$$", "OLD_NEW$$", "SEQUENCE$$", "CHANGE_VECTOR$$", "ROW$$", "LROWID$$", "HROWID$$", "PAT_TE_ID", "PAT_ID")
  SELECT /*+ NESTED_TABLE_GET_REFS  */
  "DMLTYPE$$", "OLD_NEW$$", "SEQUENCE$$", "CHANGE_VECTOR$$", "ROW$$", "LROWID$$", "HROWID$$", "PAT_TE_ID", "PAT_ID" FROM "ORA$SA$TE_REHAB_PATIENTS"@ KU$;


  CREATE GLOBAL TEMPORARY TABLE "ORA$SA$TE_REHAB_PRESCRIPTIONS"
   (	"DMLTYPE$$" VARCHAR2(1 BYTE),
	"OLD_NEW$$" VARCHAR2(1 BYTE),
	"SEQUENCE$$" NUMBER,
	"CHANGE_VECTOR$$" RAW(513),
	"ROW$$" ROWID,
	"LROWID$$" ROWID,
	"HROWID$$" ROWID,
	"PR_PRR_ID" NUMBER,
	"PR_PAT_ID" NUMBER,
	"PR_ID" NUMBER
   ) ON COMMIT DELETE ROWS ;
  INSERT /*+  APPEND  NESTED_TABLE_SET_REFS  */ INTO
  "ORA$SA$TE_REHAB_PRESCRIPTIONS"  KUT$ ("DMLTYPE$$", "OLD_NEW$$", "SEQUENCE$$", "CHANGE_VECTOR$$", "ROW$$", "LROWID$$", "HROWID$$", "PR_PRR_ID", "PR_PAT_ID", "PR_ID")
  SELECT /*+ NESTED_TABLE_GET_REFS  */
  "DMLTYPE$$", "OLD_NEW$$", "SEQUENCE$$", "CHANGE_VECTOR$$", "ROW$$", "LROWID$$", "HROWID$$", "PR_PRR_ID", "PR_PAT_ID", "PR_ID" FROM "ORA$SA$TE_REHAB_PRESCRIPTIONS"@ KU$;


  CREATE GLOBAL TEMPORARY TABLE "ORA$SA$TE_REHAB_PRESCRIPTIONS_ACTIVITY_TIME_RANGES"
   (	"DMLTYPE$$" VARCHAR2(1 BYTE),
	"OLD_NEW$$" VARCHAR2(1 BYTE),
	"SEQUENCE$$" NUMBER,
	"CHANGE_VECTOR$$" RAW(513),
	"ROW$$" ROWID,
	"LROWID$$" ROWID,
	"HROWID$$" ROWID,
	"PRATR_ACTUAL_START" TIMESTAMP (6) WITH TIME ZONE,
	"PRATR_ACTUAL_END" TIMESTAMP (6) WITH TIME ZONE,
	"PRATR_ID" NUMBER,
	"PRATR_PR_ID" NUMBER
   ) ON COMMIT DELETE ROWS ;
  INSERT /*+  APPEND  NESTED_TABLE_SET_REFS  */ INTO
  "ORA$SA$TE_REHAB_PRESCRIPTIONS_ACTIVITY_TIME_RANGES"  KUT$ ("DMLTYPE$$", "OLD_NEW$$", "SEQUENCE$$", "CHANGE_VECTOR$$", "ROW$$", "LROWID$$", "HROWID$$", "PRATR_ACTUAL_START", "PRATR_ACTUAL_END", "PRATR_ID", "PRATR_PR_ID")
  SELECT /*+ NESTED_TABLE_GET_REFS  */
  "DMLTYPE$$", "OLD_NEW$$", "SEQUENCE$$", "CHANGE_VECTOR$$", "ROW$$", "LROWID$$", "HROWID$$", "PRATR_ACTUAL_START", "PRATR_ACTUAL_END", "PRATR_ID", "PRATR_PR_ID" FROM "ORA$SA$TE_REHAB_PRESCRIPTIONS_ACTIVITY_TIME_RANGES"@ KU$;


  CREATE GLOBAL TEMPORARY TABLE "ORA$SA$TE_REHAB_PRESCRIPTORS"
   (	"DMLTYPE$$" VARCHAR2(1 BYTE),
	"OLD_NEW$$" VARCHAR2(1 BYTE),
	"SEQUENCE$$" NUMBER,
	"CHANGE_VECTOR$$" RAW(513),
	"ROW$$" ROWID,
	"LROWID$$" ROWID,
	"HROWID$$" ROWID,
	"PRR_ID" NUMBER,
	"PRR_PAT_ID" NUMBER
   ) ON COMMIT DELETE ROWS ;
  INSERT /*+  APPEND  NESTED_TABLE_SET_REFS  */ INTO
  "ORA$SA$TE_REHAB_PRESCRIPTORS"  KUT$ ("DMLTYPE$$", "OLD_NEW$$", "SEQUENCE$$", "CHANGE_VECTOR$$", "ROW$$", "LROWID$$", "HROWID$$", "PRR_ID", "PRR_PAT_ID")
  SELECT /*+ NESTED_TABLE_GET_REFS  */
  "DMLTYPE$$", "OLD_NEW$$", "SEQUENCE$$", "CHANGE_VECTOR$$", "ROW$$", "LROWID$$", "HROWID$$", "PRR_ID", "PRR_PAT_ID" FROM "ORA$SA$TE_REHAB_PRESCRIPTORS"@ KU$;


  CREATE GLOBAL TEMPORARY TABLE "ORA$SA$VC_CHECK_REHAB_CONSUME_PATTERNS_TE_PAT"
   (	"REHAB_CONSUME_PATTERNS_CP_PAT_ID" NUMBER NOT NULL ENABLE
   ) ON COMMIT DELETE ROWS ;
  INSERT /*+  APPEND  NESTED_TABLE_SET_REFS  */ INTO
  "ORA$SA$VC_CHECK_REHAB_CONSUME_PATTERNS_TE_PAT"  KUT$ ("REHAB_CONSUME_PATTERNS_CP_PAT_ID")
  SELECT /*+ NESTED_TABLE_GET_REFS  */
  "REHAB_CONSUME_PATTERNS_CP_PAT_ID" FROM "ORA$SA$VC_CHECK_REHAB_CONSUME_PATTERNS_TE_PAT"@ KU$;


  CREATE GLOBAL TEMPORARY TABLE "ORA$SA$VC_CHECK_REHAB_PRESCRIPTIONS_ACTIVITY_TIME_RANGES_OVERLAP"
   (	"REHAB_PRESCRIPTIONS_ACTIVITY_TIME_RANGES_PRATR_PR_ID" NUMBER NOT NULL ENABLE
   ) ON COMMIT DELETE ROWS ;
  INSERT /*+  APPEND  NESTED_TABLE_SET_REFS  */ INTO
  "ORA$SA$VC_CHECK_REHAB_PRESCRIPTIONS_ACTIVITY_TIME_RANGES_OVERLAP"  KUT$ ("REHAB_PRESCRIPTIONS_ACTIVITY_TIME_RANGES_PRATR_PR_ID")
  SELECT /*+ NESTED_TABLE_GET_REFS  */
  "REHAB_PRESCRIPTIONS_ACTIVITY_TIME_RANGES_PRATR_PR_ID" FROM "ORA$SA$VC_CHECK_REHAB_PRESCRIPTIONS_ACTIVITY_TIME_RANGES_OVERLAP"@ KU$;


  CREATE GLOBAL TEMPORARY TABLE "ORA$SA$VC_REHUB_CHECK_DRU_PR_PAT"
   (	"REHAB_DRUG_USES_DRU_PAT_ID" NUMBER NOT NULL ENABLE,
	"REHAB_DRUG_USES_DRU_PR_ID" NUMBER NOT NULL ENABLE
   ) ON COMMIT DELETE ROWS ;
  INSERT /*+  APPEND  NESTED_TABLE_SET_REFS  */ INTO
  "ORA$SA$VC_REHUB_CHECK_DRU_PR_PAT"  KUT$ ("REHAB_DRUG_USES_DRU_PAT_ID", "REHAB_DRUG_USES_DRU_PR_ID")
  SELECT /*+ NESTED_TABLE_GET_REFS  */
  "REHAB_DRUG_USES_DRU_PAT_ID", "REHAB_DRUG_USES_DRU_PR_ID" FROM "ORA$SA$VC_REHUB_CHECK_DRU_PR_PAT"@ KU$;


  CREATE GLOBAL TEMPORARY TABLE "ORA$SA$VC_REHUB_CHECK_PR_PRR_PAT"
   (	"REHAB_PRESCRIPTIONS_PR_PAT_ID" NUMBER NOT NULL ENABLE,
	"REHAB_PRESCRIPTIONS_PR_PRR_ID" NUMBER NOT NULL ENABLE
   ) ON COMMIT DELETE ROWS ;
  INSERT /*+  APPEND  NESTED_TABLE_SET_REFS  */ INTO
  "ORA$SA$VC_REHUB_CHECK_PR_PRR_PAT"  KUT$ ("REHAB_PRESCRIPTIONS_PR_PAT_ID", "REHAB_PRESCRIPTIONS_PR_PRR_ID")
  SELECT /*+ NESTED_TABLE_GET_REFS  */
  "REHAB_PRESCRIPTIONS_PR_PAT_ID", "REHAB_PRESCRIPTIONS_PR_PRR_ID" FROM "ORA$SA$VC_REHUB_CHECK_PR_PRR_PAT"@ KU$;


  CREATE TABLE "REHAB_CONFIGS"
   (	"PAR_NAME" VARCHAR2(30 BYTE) NOT NULL ENABLE,
	"PAR_TE_ID" NUMBER,
	"PAR_PAT_ID" NUMBER,
	"PAR_VALUE" VARCHAR2(512 BYTE),
	"PAR_DESCRIPTION" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION DEFERRED
   PCTUSED 40 INITRANS 10 MAXTRANS 255
 NOCOMPRESS  LOGGING;
ALTER TABLE "REHAB_CONFIGS" ADD CONSTRAINT "UK_REHAB_CONFIGS" UNIQUE ("PAR_NAME", "PAR_TE_ID", "PAR_PAT_ID")
  USING INDEX  INITRANS 20 MAXTRANS 255  ENABLE;
  INSERT /*+  APPEND  NESTED_TABLE_SET_REFS  */ INTO
  "REHAB_CONFIGS"  KUT$ ("PAR_NAME", "PAR_TE_ID", "PAR_PAT_ID", "PAR_VALUE", "PAR_DESCRIPTION")
  SELECT /*+ NESTED_TABLE_GET_REFS  */
  "PAR_NAME", "PAR_TE_ID", "PAR_PAT_ID", "PAR_VALUE", "PAR_DESCRIPTION" FROM "REHAB_CONFIGS"@ KU$;


  CREATE TABLE "REHAB_CONSUME_PATTERNS"
   (	"CP_ID" NUMBER NOT NULL ENABLE,
	"CP_PRNT_ID" NUMBER,
	"CP_TE_ID" NUMBER,
	"CP_PAT_ID" NUMBER,
	"CP_NAME" VARCHAR2(128 BYTE),
	"CP_DESCR" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE
   PCTUSED 40 INITRANS 10 MAXTRANS 255
 NOCOMPRESS  LOGGING;
ALTER TABLE "REHAB_CONSUME_PATTERNS" ADD CONSTRAINT "PK_REHAB_CONSUME_PATTERNS" PRIMARY KEY ("CP_ID")
  USING INDEX  INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS  ENABLE;
  INSERT /*+  APPEND  NESTED_TABLE_SET_REFS  */ INTO
  "REHAB_CONSUME_PATTERNS"  KUT$ ("CP_ID", "CP_PRNT_ID", "CP_TE_ID", "CP_PAT_ID", "CP_NAME", "CP_DESCR")
  SELECT /*+ NESTED_TABLE_GET_REFS  */
  "CP_ID", "CP_PRNT_ID", "CP_TE_ID", "CP_PAT_ID", "CP_NAME", "CP_DESCR" FROM "REHAB_CONSUME_PATTERNS"@ KU$;


  CREATE TABLE "REHAB_CONSUME_TIME_RANGES"
   (	"CPTR_ID" NUMBER NOT NULL ENABLE,
	"CPTR_CP_ID" NUMBER NOT NULL ENABLE,
	"CPTR_NAME" VARCHAR2(128 BYTE),
	"CPTR_START_TIME_STR" VARCHAR2(10 BYTE) NOT NULL ENABLE,
	"CPTR_END_TIME_STR" VARCHAR2(10 BYTE) NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE
   PCTUSED 40 INITRANS 10 MAXTRANS 255
 NOCOMPRESS  LOGGING;
ALTER TABLE "REHAB_CONSUME_TIME_RANGES" ADD CONSTRAINT "PK_REHAB_CONSUME_TIME_RANGES" PRIMARY KEY ("CPTR_ID")
  USING INDEX  INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS  ENABLE;
  INSERT /*+  APPEND  NESTED_TABLE_SET_REFS  */ INTO
  "REHAB_CONSUME_TIME_RANGES"  KUT$ ("CPTR_ID", "CPTR_CP_ID", "CPTR_NAME", "CPTR_START_TIME_STR", "CPTR_END_TIME_STR")
  SELECT /*+ NESTED_TABLE_GET_REFS  */
  "CPTR_ID", "CPTR_CP_ID", "CPTR_NAME", "CPTR_START_TIME_STR", "CPTR_END_TIME_STR" FROM "REHAB_CONSUME_TIME_RANGES"@ KU$;


  CREATE TABLE "REHAB_DRUGS"
   (	"DR_ID" NUMBER NOT NULL ENABLE,
	"DR_TE_ID" NUMBER,
	"DR_NAME" VARCHAR2(128 BYTE),
	"DR_TYPE" VARCHAR2(512 BYTE),
	"DR_TYPE_SHORT" VARCHAR2(128 BYTE),
	"DR_WORKING_SUBST" VARCHAR2(1024 BYTE),
	"DR_USE_CASE" VARCHAR2(4000 BYTE),
	"DR_WHEN2CONSUME" VARCHAR2(512 BYTE),
	"DR_INSTRUCTION" CLOB,
	"DR_INSTR_SRC_URL" VARCHAR2(512 BYTE),
	"DR_ITEM_IMAGE1" BLOB,
	"DR_ITEM_IMAGE2" BLOB,
	"DR_PACK_IMAGE1" BLOB,
	"DR_PACK_IMAGE2" BLOB
   ) SEGMENT CREATION IMMEDIATE
   PCTUSED 40 INITRANS 10 MAXTRANS 255
 NOCOMPRESS  LOGGING
 LOB ("DR_INSTRUCTION") STORE AS SECUREFILE (ENABLE STORAGE IN ROW
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES )
 LOB ("DR_ITEM_IMAGE1") STORE AS SECUREFILE (ENABLE STORAGE IN ROW
  CACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES )
 LOB ("DR_ITEM_IMAGE2") STORE AS SECUREFILE (ENABLE STORAGE IN ROW
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES )
 LOB ("DR_PACK_IMAGE1") STORE AS SECUREFILE (ENABLE STORAGE IN ROW
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES )
 LOB ("DR_PACK_IMAGE2") STORE AS SECUREFILE (ENABLE STORAGE IN ROW
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
ALTER TABLE "REHAB_DRUGS" ADD CONSTRAINT "PK_REHAB_DRUGS" PRIMARY KEY ("DR_ID")
  USING INDEX  INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS  ENABLE;
  INSERT /*+  APPEND  NESTED_TABLE_SET_REFS  */ INTO
  "REHAB_DRUGS"  KUT$ ("DR_ID", "DR_TE_ID", "DR_NAME", "DR_TYPE", "DR_TYPE_SHORT", "DR_WORKING_SUBST", "DR_USE_CASE", "DR_WHEN2CONSUME", "DR_INSTRUCTION", "DR_INSTR_SRC_URL", "DR_ITEM_IMAGE1", "DR_ITEM_IMAGE2", "DR_PACK_IMAGE1", "DR_PACK_IMAGE2")
  SELECT /*+ NESTED_TABLE_GET_REFS  */
  "DR_ID", "DR_TE_ID", "DR_NAME", "DR_TYPE", "DR_TYPE_SHORT", "DR_WORKING_SUBST", "DR_USE_CASE", "DR_WHEN2CONSUME", "DR_INSTRUCTION", "DR_INSTR_SRC_URL", "DR_ITEM_IMAGE1", "DR_ITEM_IMAGE2", "DR_PACK_IMAGE1", "DR_PACK_IMAGE2" FROM "REHAB_DRUGS"@ KU$;


  CREATE TABLE "REHAB_DRUG_ACCOUNTINGS"
   (	"DA_ID" NUMBER,
	"DA_DS_ID" NUMBER,
	"DA_DR_ID" NUMBER,
	"DA_PRR_ID" NUMBER,
	"DA_ORDER_TYPE" VARCHAR2(128 BYTE) NOT NULL ENABLE,
	"DA_QUANTITY" NUMBER NOT NULL ENABLE,
	"DA_ENTIRY_WEIGHT" NUMBER NOT NULL ENABLE,
	"DA_COST" NUMBER NOT NULL ENABLE,
	"DA_PURCHASED" TIMESTAMP (6) WITH TIME ZONE DEFAULT systimestamp,
	"DA_CHECK_POINT_DT" TIMESTAMP (6) WITH TIME ZONE,
	"DA_BEST_BEFORE" DATE
   ) SEGMENT CREATION IMMEDIATE
   PCTUSED 40 INITRANS 10 MAXTRANS 255
 NOCOMPRESS  LOGGING;
ALTER TABLE "REHAB_DRUG_ACCOUNTINGS" ADD CONSTRAINT "PK_REHAB_DRUG_ACCOUNTINGS" PRIMARY KEY ("DA_ID")
  USING INDEX  INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS  ENABLE;
  INSERT /*+  APPEND  NESTED_TABLE_SET_REFS  */ INTO
  "REHAB_DRUG_ACCOUNTINGS"  KUT$ ("DA_ID", "DA_DS_ID", "DA_DR_ID", "DA_PRR_ID", "DA_ORDER_TYPE", "DA_QUANTITY", "DA_ENTIRY_WEIGHT", "DA_COST", "DA_PURCHASED", "DA_CHECK_POINT_DT", "DA_BEST_BEFORE")
  SELECT /*+ NESTED_TABLE_GET_REFS  */
  "DA_ID", "DA_DS_ID", "DA_DR_ID", "DA_PRR_ID", "DA_ORDER_TYPE", "DA_QUANTITY", "DA_ENTIRY_WEIGHT", "DA_COST", "DA_PURCHASED", "DA_CHECK_POINT_DT", "DA_BEST_BEFORE" FROM "REHAB_DRUG_ACCOUNTINGS"@ KU$;


  CREATE TABLE "REHAB_DRUG_STORAGES"
   (	"DS_ID" NUMBER,
	"DS_TE_ID" NUMBER NOT NULL ENABLE,
	"DS_NAME" VARCHAR2(128 BYTE) NOT NULL ENABLE,
	"DS_DESCRIPTION" VARCHAR2(4000 BYTE),
	"DS_CREATED" TIMESTAMP (6) WITH TIME ZONE DEFAULT ON NULL systimestamp NOT NULL ENABLE,
	"DS_UPDATED" TIMESTAMP (6) WITH TIME ZONE
   ) SEGMENT CREATION IMMEDIATE
   PCTUSED 40 INITRANS 10 MAXTRANS 255
 NOCOMPRESS  LOGGING;
ALTER TABLE "REHAB_DRUG_STORAGES" ADD CONSTRAINT "PK_DRUG_STORAGES" PRIMARY KEY ("DS_ID")
  USING INDEX  INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS  ENABLE;
  INSERT /*+  APPEND  NESTED_TABLE_SET_REFS  */ INTO
  "REHAB_DRUG_STORAGES"  KUT$ ("DS_ID", "DS_TE_ID", "DS_NAME", "DS_DESCRIPTION", "DS_CREATED", "DS_UPDATED")
  SELECT /*+ NESTED_TABLE_GET_REFS  */
  "DS_ID", "DS_TE_ID", "DS_NAME", "DS_DESCRIPTION", "DS_CREATED", "DS_UPDATED" FROM "REHAB_DRUG_STORAGES"@ KU$;


  CREATE TABLE "REHAB_DRUG_USES"
   (	"DRU_ID" NUMBER,
	"DRU_PR_ID" NUMBER NOT NULL ENABLE,
	"DRU_PAT_ID" NUMBER NOT NULL ENABLE,
	"DRU_CPTR_ID" NUMBER NOT NULL ENABLE,
	"DRU_CONSUMED" TIMESTAMP (6) WITH TIME ZONE,
	"DRU_ACTUAL_DOSAGE" NUMBER
   ) SEGMENT CREATION IMMEDIATE
   PCTUSED 40 INITRANS 10 MAXTRANS 255
 NOCOMPRESS  LOGGING;
ALTER TABLE "REHAB_DRUG_USES" ADD CONSTRAINT "PK_REHAB_DRUG_USES" PRIMARY KEY ("DRU_ID")
  USING INDEX  INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS  ENABLE;
  INSERT /*+  APPEND  NESTED_TABLE_SET_REFS  */ INTO
  "REHAB_DRUG_USES"  KUT$ ("DRU_ID", "DRU_PR_ID", "DRU_PAT_ID", "DRU_CPTR_ID", "DRU_CONSUMED", "DRU_ACTUAL_DOSAGE")
  SELECT /*+ NESTED_TABLE_GET_REFS  */
  "DRU_ID", "DRU_PR_ID", "DRU_PAT_ID", "DRU_CPTR_ID", "DRU_CONSUMED", "DRU_ACTUAL_DOSAGE" FROM "REHAB_DRUG_USES"@ KU$;


  CREATE TABLE "REHAB_MEASUREMENTS"
   (	"MT_ID" NUMBER NOT NULL ENABLE,
	"MT_PAT_ID" NUMBER NOT NULL ENABLE,
	"MT_TAKEN" TIMESTAMP (6) WITH TIME ZONE,
	"MT_PRESSURE_LR" VARCHAR2(1 BYTE),
	"MT_PRESSURE_SYS" NUMBER,
	"MT_PRESSURE_DIA" NUMBER,
	"MT_PULSE" NUMBER,
	"MT_TEMPERATURE" NUMBER,
	"MT_SUGAR" NUMBER,
	"MT_OXIGENATION" NUMBER,
	"MT_WEIGHT" NUMBER,
	"MT_DESCR" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE
   PCTUSED 40 INITRANS 10 MAXTRANS 255
 NOCOMPRESS  LOGGING;
ALTER TABLE "REHAB_MEASUREMENTS" ADD CONSTRAINT "PK_REHAB_MEASUREMENTS" PRIMARY KEY ("MT_ID")
  USING INDEX  INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS  ENABLE;
ALTER TABLE "REHAB_MEASUREMENTS" ADD CHECK (mt_pressure_lr in ('L','R')) ENABLE;
  INSERT /*+  APPEND  NESTED_TABLE_SET_REFS  */ INTO
  "REHAB_MEASUREMENTS"  KUT$ ("MT_ID", "MT_PAT_ID", "MT_TAKEN", "MT_PRESSURE_LR", "MT_PRESSURE_SYS", "MT_PRESSURE_DIA", "MT_PULSE", "MT_TEMPERATURE", "MT_SUGAR", "MT_OXIGENATION", "MT_WEIGHT", "MT_DESCR")
  SELECT /*+ NESTED_TABLE_GET_REFS  */
  "MT_ID", "MT_PAT_ID", "MT_TAKEN", "MT_PRESSURE_LR", "MT_PRESSURE_SYS", "MT_PRESSURE_DIA", "MT_PULSE", "MT_TEMPERATURE", "MT_SUGAR", "MT_OXIGENATION", "MT_WEIGHT", "MT_DESCR" FROM "REHAB_MEASUREMENTS"@ KU$;


  CREATE TABLE "REHAB_PATIENT2STORAGES"
   (	"P2S_DS_ID" NUMBER,
	"P2S_PAT_ID" NUMBER,
	"P2S_IS_OWNER" BOOLEAN DEFAULT false -- owner can edit, not owner can see

   ) SEGMENT CREATION IMMEDIATE
   PCTUSED 40 INITRANS 10 MAXTRANS 255
 NOCOMPRESS  LOGGING;
  INSERT /*+  APPEND  NESTED_TABLE_SET_REFS  */ INTO
  "REHAB_PATIENT2STORAGES"  KUT$ ("P2S_DS_ID", "P2S_PAT_ID", "P2S_IS_OWNER")
  SELECT /*+ NESTED_TABLE_GET_REFS  */
  "P2S_DS_ID", "P2S_PAT_ID", "P2S_IS_OWNER" FROM "REHAB_PATIENT2STORAGES"@ KU$;


  CREATE TABLE "REHAB_PATIENTS"
   (	"PAT_ID" NUMBER NOT NULL ENABLE,
	"PAT_TE_ID" NUMBER NOT NULL ENABLE,
	"PAT_NAME" VARCHAR2(128 BYTE),
	"PAT_SURNAME" VARCHAR2(128 BYTE),
	"PAT_EMAIL" VARCHAR2(128 BYTE),
	"PAT_STATUS" VARCHAR2(32 BYTE),
	"PAT_CREATED" TIMESTAMP (6) WITH TIME ZONE,
	"PAT_STATUS_CHANGED" TIMESTAMP (6) WITH TIME ZONE,
	"PAT_APEX_USER" VARCHAR2(128 BYTE),
	"PAT_IS_SUPERUSER" BOOLEAN DEFAULT false
   ) SEGMENT CREATION IMMEDIATE
   PCTUSED 40 INITRANS 10 MAXTRANS 255
 NOCOMPRESS  LOGGING;
ALTER TABLE "REHAB_PATIENTS" ADD CONSTRAINT "PK_REHAB_PATIENTS" PRIMARY KEY ("PAT_ID")
  USING INDEX  INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS  ENABLE;
  INSERT /*+  APPEND  NESTED_TABLE_SET_REFS  */ INTO
  "REHAB_PATIENTS"  KUT$ ("PAT_ID", "PAT_TE_ID", "PAT_NAME", "PAT_SURNAME", "PAT_EMAIL", "PAT_STATUS", "PAT_CREATED", "PAT_STATUS_CHANGED", "PAT_APEX_USER", "PAT_IS_SUPERUSER")
  SELECT /*+ NESTED_TABLE_GET_REFS  */
  "PAT_ID", "PAT_TE_ID", "PAT_NAME", "PAT_SURNAME", "PAT_EMAIL", "PAT_STATUS", "PAT_CREATED", "PAT_STATUS_CHANGED", "PAT_APEX_USER", "PAT_IS_SUPERUSER" FROM "REHAB_PATIENTS"@ KU$;


  CREATE TABLE "REHAB_PATIENTS2P_ACCESS"
   (	"P2PA_SUBJ_PAT_ID" NUMBER NOT NULL ENABLE,
	"P2PA_TRG_PAT_ID" NUMBER NOT NULL ENABLE,
	"P2PA_CAN_MANAGE" BOOLEAN DEFAULT false
   ) SEGMENT CREATION IMMEDIATE
   PCTUSED 40 INITRANS 10 MAXTRANS 255
 NOCOMPRESS  LOGGING;
ALTER TABLE "REHAB_PATIENTS2P_ACCESS" ADD CONSTRAINT "PK_REHAB_PATIENTS2P_ACCESS" PRIMARY KEY ("P2PA_SUBJ_PAT_ID", "P2PA_TRG_PAT_ID")
  USING INDEX  INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS  ENABLE;
  INSERT /*+  APPEND  NESTED_TABLE_SET_REFS  */ INTO
  "REHAB_PATIENTS2P_ACCESS"  KUT$ ("P2PA_SUBJ_PAT_ID", "P2PA_TRG_PAT_ID", "P2PA_CAN_MANAGE")
  SELECT /*+ NESTED_TABLE_GET_REFS  */
  "P2PA_SUBJ_PAT_ID", "P2PA_TRG_PAT_ID", "P2PA_CAN_MANAGE" FROM "REHAB_PATIENTS2P_ACCESS"@ KU$;


  CREATE TABLE "REHAB_PRESCRIPTIONS"
   (	"PR_ID" NUMBER NOT NULL ENABLE,
	"PR_DR_ID" NUMBER NOT NULL ENABLE,
	"PR_PAT_ID" NUMBER NOT NULL ENABLE,
	"PR_PRR_ID" NUMBER NOT NULL ENABLE,
	"PR_PLANNED_START" TIMESTAMP (6) WITH TIME ZONE,
	"PR_PLANNED_END" TIMESTAMP (6) WITH TIME ZONE,
	"PR_NOTES" VARCHAR2(512 BYTE)
   ) SEGMENT CREATION IMMEDIATE
   PCTUSED 40 INITRANS 10 MAXTRANS 255
 NOCOMPRESS  LOGGING;
ALTER TABLE "REHAB_PRESCRIPTIONS" ADD CONSTRAINT "PK_REHAB_PRESCRIPTIONS" PRIMARY KEY ("PR_ID")
  USING INDEX  INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS  ENABLE;
  INSERT /*+  APPEND  NESTED_TABLE_SET_REFS  */ INTO
  "REHAB_PRESCRIPTIONS"  KUT$ ("PR_ID", "PR_DR_ID", "PR_PAT_ID", "PR_PRR_ID", "PR_PLANNED_START", "PR_PLANNED_END", "PR_NOTES")
  SELECT /*+ NESTED_TABLE_GET_REFS  */
  "PR_ID", "PR_DR_ID", "PR_PAT_ID", "PR_PRR_ID", "PR_PLANNED_START", "PR_PLANNED_END", "PR_NOTES" FROM "REHAB_PRESCRIPTIONS"@ KU$;


  CREATE TABLE "REHAB_PRESCRIPTIONS_ACTIVITY_TIME_RANGES"
   (	"PRATR_ID" NUMBER NOT NULL ENABLE,
	"PRATR_PR_ID" NUMBER NOT NULL ENABLE,
	"PRATR_CP_ID" NUMBER NOT NULL ENABLE,
	"PRATR_ACTUAL_START" TIMESTAMP (6) WITH TIME ZONE,
	"PRATR_ACTUAL_END" TIMESTAMP (6) WITH TIME ZONE,
	"PRATR_NOTES" VARCHAR2(512 BYTE)
   ) SEGMENT CREATION IMMEDIATE
   PCTUSED 40 INITRANS 10 MAXTRANS 255
 NOCOMPRESS  LOGGING;
  ALTER TABLE "REHAB_PRESCRIPTIONS_ACTIVITY_TIME_RANGES" ADD PERIOD FOR "REHAB_PRESCRIPTIONS_ACTIVITY_TIME_RANGES_PERIOD"("PRATR_ACTUAL_START","PRATR_ACTUAL_END") ;
ALTER TABLE "REHAB_PRESCRIPTIONS_ACTIVITY_TIME_RANGES" ADD CONSTRAINT "PK_REHAB_PRESCRIPTIONS_ACTIVITY_TIME_RANGES" PRIMARY KEY ("PRATR_ID")
  USING INDEX  INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS  ENABLE;
  INSERT /*+  APPEND  NESTED_TABLE_SET_REFS  */ INTO
  "REHAB_PRESCRIPTIONS_ACTIVITY_TIME_RANGES"  KUT$ ("PRATR_ID", "PRATR_PR_ID", "PRATR_CP_ID", "PRATR_ACTUAL_START", "PRATR_ACTUAL_END", "PRATR_NOTES")
  SELECT /*+ NESTED_TABLE_GET_REFS  */
  "PRATR_ID", "PRATR_PR_ID", "PRATR_CP_ID", "PRATR_ACTUAL_START", "PRATR_ACTUAL_END", "PRATR_NOTES" FROM "REHAB_PRESCRIPTIONS_ACTIVITY_TIME_RANGES"@ KU$;


  CREATE TABLE "REHAB_PRESCRIPTIONS_DETAILS"
   (	"PRD_ID" NUMBER NOT NULL ENABLE,
	"PRD_PRATR_ID" NUMBER NOT NULL ENABLE,
	"PRD_CPTR_ID" NUMBER NOT NULL ENABLE,
	"PRD_DOSAGE" NUMBER NOT NULL ENABLE,
	"PRD_SORT_ORDER" NUMBER DEFAULT 0,
	"PRD_NOTES" VARCHAR2(512 BYTE)
   ) SEGMENT CREATION IMMEDIATE
   PCTUSED 40 INITRANS 10 MAXTRANS 255
 NOCOMPRESS  LOGGING;
ALTER TABLE "REHAB_PRESCRIPTIONS_DETAILS" ADD CONSTRAINT "PK_REHAB_PRESCRIPTIONS_DETAILS" PRIMARY KEY ("PRD_ID")
  USING INDEX  INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS  ENABLE;
  INSERT /*+  APPEND  NESTED_TABLE_SET_REFS  */ INTO
  "REHAB_PRESCRIPTIONS_DETAILS"  KUT$ ("PRD_ID", "PRD_PRATR_ID", "PRD_CPTR_ID", "PRD_DOSAGE", "PRD_SORT_ORDER", "PRD_NOTES")
  SELECT /*+ NESTED_TABLE_GET_REFS  */
  "PRD_ID", "PRD_PRATR_ID", "PRD_CPTR_ID", "PRD_DOSAGE", "PRD_SORT_ORDER", "PRD_NOTES" FROM "REHAB_PRESCRIPTIONS_DETAILS"@ KU$;


  CREATE TABLE "REHAB_PRESCRIPTOR2DRUG_FLTS"
   (	"PRRF_PRR_ID" NUMBER NOT NULL ENABLE,
	"PRRF_DR_ID" NUMBER NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE
   PCTUSED 40 INITRANS 10 MAXTRANS 255
 NOCOMPRESS  LOGGING;
  INSERT /*+  APPEND  NESTED_TABLE_SET_REFS  */ INTO
  "REHAB_PRESCRIPTOR2DRUG_FLTS"  KUT$ ("PRRF_PRR_ID", "PRRF_DR_ID")
  SELECT /*+ NESTED_TABLE_GET_REFS  */
  "PRRF_PRR_ID", "PRRF_DR_ID" FROM "REHAB_PRESCRIPTOR2DRUG_FLTS"@ KU$;


  CREATE TABLE "REHAB_PRESCRIPTORS"
   (	"PRR_ID" NUMBER NOT NULL ENABLE,
	"PRR_PRESCRIPTED_BY_SHORT" VARCHAR2(4000 BYTE),
	"PRR_PRESCRIPTED_WHEN" TIMESTAMP (6) WITH TIME ZONE,
	"PRR_PRESCRIPTED_BY_FULL" VARCHAR2(4000 BYTE),
	"PRR_PAT_ID" NUMBER NOT NULL ENABLE,
	"PRR_FULL_TEXT" CLOB,
	"PRR_PAGE1" BLOB,
	"PRR_PAGE2" BLOB,
	"PRR_PAGE3" BLOB,
	"PRR_PAGE4" BLOB,
	"PRR_PAGE5" BLOB
   ) SEGMENT CREATION IMMEDIATE
   PCTUSED 40 INITRANS 10 MAXTRANS 255
 NOCOMPRESS  LOGGING
 LOB ("PRR_FULL_TEXT") STORE AS SECUREFILE (ENABLE STORAGE IN ROW
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES )
 LOB ("PRR_PAGE1") STORE AS SECUREFILE (ENABLE STORAGE IN ROW
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES )
 LOB ("PRR_PAGE2") STORE AS SECUREFILE (ENABLE STORAGE IN ROW
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES )
 LOB ("PRR_PAGE3") STORE AS SECUREFILE (ENABLE STORAGE IN ROW
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES )
 LOB ("PRR_PAGE4") STORE AS SECUREFILE (ENABLE STORAGE IN ROW
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES )
 LOB ("PRR_PAGE5") STORE AS SECUREFILE (ENABLE STORAGE IN ROW
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
ALTER TABLE "REHAB_PRESCRIPTORS" ADD CONSTRAINT "PK_REHAB_PRESCRIPTORS" PRIMARY KEY ("PRR_ID")
  USING INDEX  INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS  ENABLE;
  INSERT /*+  APPEND  NESTED_TABLE_SET_REFS  */ INTO
  "REHAB_PRESCRIPTORS"  KUT$ ("PRR_ID", "PRR_PRESCRIPTED_BY_SHORT", "PRR_PRESCRIPTED_WHEN", "PRR_PRESCRIPTED_BY_FULL", "PRR_PAT_ID", "PRR_FULL_TEXT", "PRR_PAGE1", "PRR_PAGE2", "PRR_PAGE3", "PRR_PAGE4", "PRR_PAGE5")
  SELECT /*+ NESTED_TABLE_GET_REFS  */
  "PRR_ID", "PRR_PRESCRIPTED_BY_SHORT", "PRR_PRESCRIPTED_WHEN", "PRR_PRESCRIPTED_BY_FULL", "PRR_PAT_ID", "PRR_FULL_TEXT", "PRR_PAGE1", "PRR_PAGE2", "PRR_PAGE3", "PRR_PAGE4", "PRR_PAGE5" FROM "REHAB_PRESCRIPTORS"@ KU$;


  CREATE TABLE "REHAB_TENANTS"
   (	"TE_ID" NUMBER NOT NULL ENABLE,
	"TE_NAME" VARCHAR2(128 BYTE),
	"TE_DESCR" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE
   PCTUSED 40 INITRANS 10 MAXTRANS 255
 NOCOMPRESS  LOGGING;
ALTER TABLE "REHAB_TENANTS" ADD CONSTRAINT "PK_REHAB_TENANTS" PRIMARY KEY ("TE_ID")
  USING INDEX  INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS  ENABLE;
  INSERT /*+  APPEND  NESTED_TABLE_SET_REFS  */ INTO
  "REHAB_TENANTS"  KUT$ ("TE_ID", "TE_NAME", "TE_DESCR")
  SELECT /*+ NESTED_TABLE_GET_REFS  */
  "TE_ID", "TE_NAME", "TE_DESCR" FROM "REHAB_TENANTS"@ KU$;


  CREATE TABLE "REHAB_TRAININGS"
   (	"TR_ID" NUMBER,
	"TR_TYPE" VARCHAR2(128 BYTE),
	"TR_PAT_ID" NUMBER,
	"TR_START" TIMESTAMP (6) WITH TIME ZONE,
	"TR_END" TIMESTAMP (6) WITH TIME ZONE,
	"TR_DISTANCE_LENGTH" NUMBER,
	"TR_STEPS" NUMBER,
	"TR_PULSE_AVG" NUMBER,
	"TR_PULSE_MIN" NUMBER,
	"TR_PULSE_MAX" NUMBER
   ) SEGMENT CREATION IMMEDIATE
   PCTUSED 40 INITRANS 10 MAXTRANS 255
 NOCOMPRESS  LOGGING;
ALTER TABLE "REHAB_TRAININGS" ADD CONSTRAINT "PK_REHAB_TRAININGS" PRIMARY KEY ("TR_ID")
  USING INDEX  INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS  ENABLE;
  INSERT /*+  APPEND  NESTED_TABLE_SET_REFS  */ INTO
  "REHAB_TRAININGS"  KUT$ ("TR_ID", "TR_TYPE", "TR_PAT_ID", "TR_START", "TR_END", "TR_DISTANCE_LENGTH", "TR_STEPS", "TR_PULSE_AVG", "TR_PULSE_MIN", "TR_PULSE_MAX")
  SELECT /*+ NESTED_TABLE_GET_REFS  */
  "TR_ID", "TR_TYPE", "TR_PAT_ID", "TR_START", "TR_END", "TR_DISTANCE_LENGTH", "TR_STEPS", "TR_PULSE_AVG", "TR_PULSE_MIN", "TR_PULSE_MAX" FROM "REHAB_TRAININGS"@ KU$;


  CREATE TABLE "REHAB_WATCH_LOGS"
   (	"WL_ID" NUMBER NOT NULL ENABLE,
	"WL_PAT_ID" NUMBER NOT NULL ENABLE,
	"WL_TAKEN" TIMESTAMP (6) WITH TIME ZONE,
	"WL_STEPS" NUMBER,
	"WL_NIGHT_MIN_PULSE" NUMBER,
	"WL_NIGHT_MAX_PULSE" NUMBER,
	"WL_NIGHT_AVG_PULSE" NUMBER
   ) SEGMENT CREATION IMMEDIATE
   PCTUSED 40 INITRANS 10 MAXTRANS 255
 NOCOMPRESS  LOGGING;
ALTER TABLE "REHAB_WATCH_LOGS" ADD CONSTRAINT "PK_REHAB_WATCH_LOGS" PRIMARY KEY ("WL_ID")
  USING INDEX  INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS  ENABLE;
  INSERT /*+  APPEND  NESTED_TABLE_SET_REFS  */ INTO
  "REHAB_WATCH_LOGS"  KUT$ ("WL_ID", "WL_PAT_ID", "WL_TAKEN", "WL_STEPS", "WL_NIGHT_MIN_PULSE", "WL_NIGHT_MAX_PULSE", "WL_NIGHT_AVG_PULSE")
  SELECT /*+ NESTED_TABLE_GET_REFS  */
  "WL_ID", "WL_PAT_ID", "WL_TAKEN", "WL_STEPS", "WL_NIGHT_MIN_PULSE", "WL_NIGHT_MAX_PULSE", "WL_NIGHT_AVG_PULSE" FROM "REHAB_WATCH_LOGS"@ KU$;



  ALTER TABLE "REHAB_CONFIGS" ADD CONSTRAINT "FK_REHAB_CONFIGS_TE" FOREIGN KEY ("PAR_TE_ID")
	  REFERENCES "REHAB_TENANTS" ("TE_ID") ENABLE;


  ALTER TABLE "REHAB_CONFIGS" ADD CONSTRAINT "FK_REHAB_CONFIGS_PAT" FOREIGN KEY ("PAR_PAT_ID")
	  REFERENCES "REHAB_PATIENTS" ("PAT_ID") ENABLE;


  ALTER TABLE "REHAB_CONSUME_PATTERNS" ADD CONSTRAINT "FK_REHAB_CONSUME_PATTERNS_PRNT" FOREIGN KEY ("CP_PRNT_ID")
	  REFERENCES "REHAB_CONSUME_PATTERNS" ("CP_ID") ENABLE;


  ALTER TABLE "REHAB_CONSUME_PATTERNS" ADD CONSTRAINT "FK_REHAB_CONSUME_PATTERNS_PAT" FOREIGN KEY ("CP_PAT_ID")
	  REFERENCES "REHAB_PATIENTS" ("PAT_ID") ENABLE;


  ALTER TABLE "REHAB_CONSUME_PATTERNS" ADD CONSTRAINT "FK_REHAB_CONSUME_PATTERNS_TE" FOREIGN KEY ("CP_TE_ID")
	  REFERENCES "REHAB_TENANTS" ("TE_ID") ENABLE;


  ALTER TABLE "REHAB_CONSUME_TIME_RANGES" ADD CONSTRAINT "FK_REHAB_CONSUME_TIME_RANGES_CP" FOREIGN KEY ("CPTR_CP_ID")
	  REFERENCES "REHAB_CONSUME_PATTERNS" ("CP_ID") ENABLE;


  ALTER TABLE "REHAB_DRUGS" ADD CONSTRAINT "FK_REHAB_DRUGS_TE" FOREIGN KEY ("DR_TE_ID")
	  REFERENCES "REHAB_TENANTS" ("TE_ID") ENABLE;


  ALTER TABLE "REHAB_DRUG_ACCOUNTINGS" ADD CONSTRAINT "FK_REHAB_DRUG_ACCS_STORAGE" FOREIGN KEY ("DA_DS_ID")
	  REFERENCES "REHAB_DRUG_STORAGES" ("DS_ID") ENABLE;


  ALTER TABLE "REHAB_DRUG_ACCOUNTINGS" ADD CONSTRAINT "FK_REHAB_DRUG_ACCS_DRUG" FOREIGN KEY ("DA_DR_ID")
	  REFERENCES "REHAB_DRUGS" ("DR_ID") ENABLE;


  ALTER TABLE "REHAB_DRUG_ACCOUNTINGS" ADD CONSTRAINT "FK_REHAB_DRUG_ACCS_PRESCRIPTOR" FOREIGN KEY ("DA_PRR_ID")
	  REFERENCES "REHAB_PRESCRIPTORS" ("PRR_ID") ENABLE;


  ALTER TABLE "REHAB_DRUG_STORAGES" ADD CONSTRAINT "FK_REHAB_DRUG_STORAGES_TE" FOREIGN KEY ("DS_TE_ID")
	  REFERENCES "REHAB_TENANTS" ("TE_ID") ENABLE;


  ALTER TABLE "REHAB_DRUG_USES" ADD CONSTRAINT "FK_REHAB_DRUG_USE_PATIENT" FOREIGN KEY ("DRU_PAT_ID")
	  REFERENCES "REHAB_PATIENTS" ("PAT_ID") ENABLE;


  ALTER TABLE "REHAB_DRUG_USES" ADD CONSTRAINT "FK_REHAB_DRUG_USES_CPTR" FOREIGN KEY ("DRU_CPTR_ID")
	  REFERENCES "REHAB_CONSUME_TIME_RANGES" ("CPTR_ID") ENABLE;


  ALTER TABLE "REHAB_DRUG_USES" ADD CONSTRAINT "FK_REHAB_DRUG_USE_PRESCRIPTION" FOREIGN KEY ("DRU_PR_ID")
	  REFERENCES "REHAB_PRESCRIPTIONS" ("PR_ID") ENABLE;


  ALTER TABLE "REHAB_MEASUREMENTS" ADD CONSTRAINT "FK_REHAB_MEASUREMENTS_PATIENT" FOREIGN KEY ("MT_PAT_ID")
	  REFERENCES "REHAB_PATIENTS" ("PAT_ID") ENABLE;


  ALTER TABLE "REHAB_PATIENT2STORAGES" ADD CONSTRAINT "FK_REHAB_PATIENT2STORAGES_STORAGE" FOREIGN KEY ("P2S_DS_ID")
	  REFERENCES "REHAB_DRUG_STORAGES" ("DS_ID") ENABLE;


  ALTER TABLE "REHAB_PATIENT2STORAGES" ADD CONSTRAINT "FK_REHAB_PATIENT2STORAGES_PAT" FOREIGN KEY ("P2S_PAT_ID")
	  REFERENCES "REHAB_PATIENTS" ("PAT_ID") ENABLE;


  ALTER TABLE "REHAB_PATIENTS" ADD CONSTRAINT "FK_REHAB_PATIENTS_TE" FOREIGN KEY ("PAT_TE_ID")
	  REFERENCES "REHAB_TENANTS" ("TE_ID") ENABLE;


  ALTER TABLE "REHAB_PATIENTS2P_ACCESS" ADD CONSTRAINT "FK_REHAB_PATIENTS2P_ACCESS_SUBJPAT" FOREIGN KEY ("P2PA_SUBJ_PAT_ID")
	  REFERENCES "REHAB_PATIENTS" ("PAT_ID") ENABLE;


  ALTER TABLE "REHAB_PATIENTS2P_ACCESS" ADD CONSTRAINT "FK_REHAB_PATIENTS2P_ACCESS_TRGPAT" FOREIGN KEY ("P2PA_TRG_PAT_ID")
	  REFERENCES "REHAB_PATIENTS" ("PAT_ID") ENABLE;


  ALTER TABLE "REHAB_PRESCRIPTIONS" ADD CONSTRAINT "FK_REHAB_PRESCRIPTION_DR" FOREIGN KEY ("PR_DR_ID")
	  REFERENCES "REHAB_DRUGS" ("DR_ID") ENABLE;


  ALTER TABLE "REHAB_PRESCRIPTIONS" ADD CONSTRAINT "FK_REHAB_PRESCRIPTIONS_PAT" FOREIGN KEY ("PR_PAT_ID")
	  REFERENCES "REHAB_PATIENTS" ("PAT_ID") ENABLE;


  ALTER TABLE "REHAB_PRESCRIPTIONS" ADD CONSTRAINT "FK_REHAB_PRESCRIPTION_PR" FOREIGN KEY ("PR_PRR_ID")
	  REFERENCES "REHAB_PRESCRIPTORS" ("PRR_ID") ENABLE;


  ALTER TABLE "REHAB_PRESCRIPTIONS_ACTIVITY_TIME_RANGES" ADD CONSTRAINT "FK_REHAB_PRESCRIPTIONS_ACTIVITY_TIME_RANGES_PR" FOREIGN KEY ("PRATR_PR_ID")
	  REFERENCES "REHAB_PRESCRIPTIONS" ("PR_ID") ENABLE;


  ALTER TABLE "REHAB_PRESCRIPTIONS_ACTIVITY_TIME_RANGES" ADD CONSTRAINT "FK_REHAB_PRESCRIPTIONS_ACTIVITY_TIME_RANGES_CP" FOREIGN KEY ("PRATR_CP_ID")
	  REFERENCES "REHAB_CONSUME_PATTERNS" ("CP_ID") ENABLE;


  ALTER TABLE "REHAB_PRESCRIPTIONS_DETAILS" ADD CONSTRAINT "FK_REHAB_PRESCRIPTIONS_DETAILS_PRATR" FOREIGN KEY ("PRD_PRATR_ID")
	  REFERENCES "REHAB_PRESCRIPTIONS_ACTIVITY_TIME_RANGES" ("PRATR_ID") ENABLE;


  ALTER TABLE "REHAB_PRESCRIPTIONS_DETAILS" ADD CONSTRAINT "FK_REHAB_PRESCRIPTIONS_DETAILS_CPTR" FOREIGN KEY ("PRD_CPTR_ID")
	  REFERENCES "REHAB_CONSUME_TIME_RANGES" ("CPTR_ID") ENABLE;


  ALTER TABLE "REHAB_PRESCRIPTOR2DRUG_FLTS" ADD CONSTRAINT "FK_REHAB_PRRFLT_PRR" FOREIGN KEY ("PRRF_PRR_ID")
	  REFERENCES "REHAB_PRESCRIPTORS" ("PRR_ID") ENABLE;


  ALTER TABLE "REHAB_PRESCRIPTOR2DRUG_FLTS" ADD CONSTRAINT "FK_REHAB_PRRFLT_DRUG" FOREIGN KEY ("PRRF_DR_ID")
	  REFERENCES "REHAB_DRUGS" ("DR_ID") ENABLE;


  ALTER TABLE "REHAB_PRESCRIPTORS" ADD CONSTRAINT "FK_REHAB_PRR_PAT" FOREIGN KEY ("PRR_PAT_ID")
	  REFERENCES "REHAB_PATIENTS" ("PAT_ID") ENABLE;


  ALTER TABLE "REHAB_TRAININGS" ADD CONSTRAINT "FK_REHAB_TRAININGS_PAT_ID" FOREIGN KEY ("TR_PAT_ID")
	  REFERENCES "REHAB_PATIENTS" ("PAT_ID") ENABLE;


  ALTER TABLE "REHAB_WATCH_LOGS" ADD CONSTRAINT "FK_REHAB_WATCH_LOGS_PAT" FOREIGN KEY ("WL_PAT_ID")
	  REFERENCES "REHAB_PATIENTS" ("PAT_ID") ENABLE;



  CREATE UNIQUE INDEX "IX_APEX_STORED_STATES_TYPES" ON "APEX_STORED_STATES" ("APP_USER", "APP_PAGE", DECODE("STORAGE_TYPE",'DEFAULT',"STORAGE_TYPE","STORAGE_NAME"))
  PCTFREE 10 INITRANS 20 MAXTRANS 255 ;


  CREATE INDEX "IDX_REHAB_DRUG_ACCOUNTINGS_DRUG" ON "REHAB_DRUG_ACCOUNTINGS" ("DA_DR_ID")
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS ;


  CREATE INDEX "IDX_REHAB_DRUG_ACCOUNTINGS_DS" ON "REHAB_DRUG_ACCOUNTINGS" ("DA_DS_ID")
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS ;


  CREATE INDEX "IDX_REHAB_DRUG_ACCOUNTINGS_PRR" ON "REHAB_DRUG_ACCOUNTINGS" ("DA_PRR_ID")
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS ;


  CREATE INDEX "IDX_REHAB_DRUG_USES_PAT" ON "REHAB_DRUG_USES" ("DRU_PAT_ID")
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS ;


  CREATE INDEX "IDX_REHAB_DRUG_USES_PAT_PR" ON "REHAB_DRUG_USES" ("DRU_PAT_ID", "DRU_PR_ID")
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS ;


  CREATE INDEX "IDX_REHAB_DRUG_USES_PR" ON "REHAB_DRUG_USES" ("DRU_PR_ID")
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS ;


  CREATE INDEX "IDX_REHAB_MEASUREMENTS_PAT" ON "REHAB_MEASUREMENTS" ("MT_PAT_ID")
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS ;


  CREATE INDEX "IDX_REHAB_PATIENT2STORAGES_PAT_DS" ON "REHAB_PATIENT2STORAGES" ("P2S_PAT_ID", "P2S_DS_ID")
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS ;


  CREATE INDEX "IDX_REHAB_PATIENTS_APEX_USR" ON "REHAB_PATIENTS" ("PAT_APEX_USER")
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS ;


  CREATE INDEX "IDX_REHAB_PRESCRIPTIONS_DR" ON "REHAB_PRESCRIPTIONS" ("PR_DR_ID")
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS ;


  CREATE INDEX "IDX_REHAB_PRESCRIPTIONS_PAT" ON "REHAB_PRESCRIPTIONS" ("PR_PAT_ID")
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS ;


  CREATE INDEX "IDX_REHAB_PRESCRIPTIONS_PRR" ON "REHAB_PRESCRIPTIONS" ("PR_PRR_ID")
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS ;


  CREATE INDEX "IDX_REHAB_TRAININGS_PAT" ON "REHAB_TRAININGS" ("TR_PAT_ID")
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS ;


  CREATE INDEX "IDX_REHAB_WATCH_LOGS_PAT" ON "REHAB_WATCH_LOGS" ("WL_PAT_ID")
  PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS ;



  CREATE OR REPLACE FORCE EDITIONABLE VIEW "V$REHAB_CONSUME_TIME_RANGES" ("CPTR_ID", "CPTR_CP_ID", "CPTR_NAME", "CPTR_START_TIME_STR", "CPTR_END_TIME_STR", "CPTR_START_TIME_DT", "CPTR_END_TIME_DT") AS
  select x."CPTR_ID",x."CPTR_CP_ID",x."CPTR_NAME",x."CPTR_START_TIME_STR",x."CPTR_END_TIME_STR",
    (to_timestamp_tz(to_char(systimestamp at time zone SESSIONTIMEZONE,'YYYYMMDD')||CPTR_START_TIME_STR||' '||sessiontimezone,'YYYYMMDDHH24:MI TZH:TZM')) CPTR_START_TIME_DT,
    (to_timestamp_tz(to_char(systimestamp at time zone SESSIONTIMEZONE,'YYYYMMDD')||CPTR_END_TIME_STR||' '||sessiontimezone,'YYYYMMDDHH24:MI TZH:TZM')) CPTR_END_TIME_DT
  from REHAB_CONSUME_TIME_RANGES x;



   CREATE SEQUENCE  "SQ_APEX_STORED_STATES"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
alter sequence SQ_APEX_STORED_STATES restart;


   CREATE SEQUENCE  "SQ_REHAB_CONSUME_PATTERNS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 24 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
alter sequence SQ_REHAB_CONSUME_PATTERNS restart;


   CREATE SEQUENCE  "SQ_REHAB_CONSUME_TIME_RANGES"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
alter sequence SQ_REHAB_CONSUME_TIME_RANGES restart;


   CREATE SEQUENCE  "SQ_REHAB_DRUGS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 202 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
alter sequence SQ_REHAB_DRUGS restart;


   CREATE SEQUENCE  "SQ_REHAB_DRUG_ACCOUNTINGS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 203 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
alter sequence SQ_REHAB_DRUG_ACCOUNTINGS restart;


   CREATE SEQUENCE  "SQ_REHAB_DRUG_STORAGES"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 62 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
alter sequence SQ_REHAB_DRUG_STORAGES restart;


   CREATE SEQUENCE  "SQ_REHAB_DRUG_USES"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 4667 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
alter sequence SQ_REHAB_DRUG_USES restart;


   CREATE SEQUENCE  "SQ_REHAB_MEASUREMENTS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 3590 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
alter sequence SQ_REHAB_MEASUREMENTS restart;


   CREATE SEQUENCE  "SQ_REHAB_PATIENTS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 22 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
alter sequence SQ_REHAB_PATIENTS restart;


   CREATE SEQUENCE  "SQ_REHAB_PRESCRIPTIONS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 282 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
alter sequence SQ_REHAB_PRESCRIPTIONS restart;


   CREATE SEQUENCE  "SQ_REHAB_PRESCRIPTIONS_ACTIVITY_TIME_RANGES"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 221 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
alter sequence SQ_REHAB_PRESCRIPTIONS_ACTIVITY_TIME_RANGES restart;


   CREATE SEQUENCE  "SQ_REHAB_PRESCRIPTIONS_DETAILS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 66 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
alter sequence SQ_REHAB_PRESCRIPTIONS_DETAILS restart;


   CREATE SEQUENCE  "SQ_REHAB_PRESCRIPTORS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 182 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
alter sequence SQ_REHAB_PRESCRIPTORS restart;


   CREATE SEQUENCE  "SQ_REHAB_TENANTS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
alter sequence SQ_REHAB_TENANTS restart;


   CREATE SEQUENCE  "SQ_REHAB_TRAININGS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1723 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
alter sequence SQ_REHAB_TRAININGS restart;


   CREATE SEQUENCE  "SQ_REHAB_WATCH_LOGS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1702 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
alter sequence SQ_REHAB_WATCH_LOGS restart;

