set define off
@@REHAB_DASHBOARD_REC_SPEC.SQL
show errors
@@REHAB_DASHBOARD_TAB_SPEC.SQL
show errors
@@REHAB_DRUGUSE_DASHBOARD_REC_SPEC.SQL
show errors
@@REHAB_DRUGUSE_DASHBOARD_TAB_SPEC.SQL
show errors
@@REHAB_CONFIG_PKG_SPEC.SQL
show errors
@@REHAB_CONTEXT_PKG_SPEC.SQL
show errors
@@REHAB_DRUGUSE_PKG_SPEC.SQL
show errors
@@REHAB_MIGRATE_PKG_SPEC.SQL
show errors
@@REHAB_PRESCRIPTIONS_PKG_SPEC.SQL
show errors
@@REHAB_UI_REPORTS_PKG_SPEC.SQL
show errors
@@REHAB_CONFIG_PKG_BODY.SQL
show errors
@@REHAB_CONTEXT_PKG_BODY.SQL
show errors
@@REHAB_DRUGUSE_PKG_BODY.SQL
show errors
@@REHAB_MIGRATE_PKG_BODY.SQL
show errors
@@REHAB_PRESCRIPTIONS_PKG_BODY.SQL
show errors
@@REHAB_UI_REPORTS_PKG_BODY.SQL
show errors
set define on
