


  CREATE OR REPLACE EDITIONABLE TYPE "REHAB_DASHBOARD_REC"
  OID '5C784590E0079AADE0632462000A1EE4' AS OBJECT (
    id           number,
    mainlabel    VARCHAR2(4000),
    sublabel     varchar2(4000),
    data1        VARCHAR2(4000),
    data2        VARCHAR2(4000),
    iconfile     VARCHAR2(4000),
    bagecol      VARCHAR2(4000),
    bagelabel    VARCHAR2(4000),
    app_page     number
);
/


